### PR TITLE
SSH hardening additions

### PR DESCRIPTION
**Pull request by ngkogkos**

### CODE REVIEW

**Comment by virajkulkarni14** [comment]
@mobrien, this is the 3rd one, which you could give your perspective. In general, we should also decide the direction of this list: should we create a new section per list item as to how a bad practice should be remediated?
For e.g., like in this one:
Don’t keep port 22 open on any AWS service groups on a permanent basis. 
**Solution**: Consider only allowing authorized IPs to SSH on the box, by whitelisting them, for example with iptables. Disable root SSH access and consider relying on Public-Key Authentication only if SSH access is not IP restricted.

**Comment by virajkulkarni14** [comment]
Also, on @mobrien's original blog post, some people have requested if you could add links to an article/tutorial that covers each respective point, that would help some of us get started who might not know how to implement some of the recommendation. Where should those be added?

**Comment by virajkulkarni14** [comment]
Finally, @ngkogkos, please correct typos in this submission like "authorised". Thanks! 🙂

**Comment by ngkogkos** [comment]
@virajkulkarni14 Thanks for that. You mean changing it to "authorized" ? I am trying to be in favour of England english when it comes down to stuff like this, but really up to you, just let me know.

**Comment by mobrien** [comment]
I'd recommend that we keep the list short and terse and put examples, remediation in a parallel document.

My thoughts in the implementation parallel document was to have a page per item that has "what", "why", "how" and "reference" sections. This would explain what the item is and explain technical terms, why it is important and how to implement including various options for different platforms / frameworks.

These parallel implementation notes could then get very detailed and have tons of great information, but the core list could be kept very tight.

Regarding ssh. The core point is to have people consider why they are using SSH and to make sure they are automating everything possible. I think it is reasonable to add the "if you must use ssh, then ....whitelist .... through a bastion host".

**Pull request merged**
