### PR TITLE
Adding CAPTCHA point

### PR DESCRIPTION
**Pull request by ngkogkos**

### CODE REVIEW

**Comment by virajkulkarni14** [comment]
@mobrien, I wanted your perspective on this before I add it to this list. There are 2 more such contributions where I will tag you to request your take on them.

@ngkogkos, thanks for the PRs, we'll wait some time before merging this and the other 2 from you. I would like to foster discussion about every point we add to this list. Thank you for your patience.
🙂

**Comment by ngkogkos** [comment]
@virajkulkarni14 that's alright, let me know what you think about that but usually I am in favour of implementing CAPTCHA in the application instead of relying on other external protections such as Cloudflare. Although with APIs the rest of things in list make perfect sense.

**Comment by mobrien** [comment]
Captcha isn't needed in many sites. So this would either need more clarification / scoping. It is useful in validating users, but is somewhat tangential to site security.

Captcha can be useful in DoS protection, however, it can makes the DoS worse in terms of CPU impact, unless handled by proxy cache like CloudFlare. 

I'd recommend we not include this item.

For general guidance: we need to keep the list as small as possible. If we add +50 items, it will become less valuable. So each item needs to be really applicable. Some of the existing items don't really pass this test either.

**Comment by ngkogkos** [comment]
I agree with your point about CAPTCHA being specific to the specifics of each application, however:

- How does it make DoS worse in terms of CPU impact?
- I am always keen to avoid guiding people into relying on commercial "smart" protection solutions for a variety of reasons, for example using Cloudflare (I am not against it but for a simple web app I would never recommend it) would mean that client data pass through Cloudflare servers and therefore this is out of the organisations control.
- CAPTCHA has few advantages. First it is free and quick to implement properly, if devs don't suck. Second, it doesn't only protect from pure DoS attacks in terms of resources, but it protects from DoSing the companies back-end office for example by submitting junk data that would go to sales people. It also hinders other enumeration attacks.

Keeping it short however is crucial as you've said. What if there was an extra section that recommends Further Application Hardening stuff? It could be also used as an alternative in one of the points in few words, something like "... alternatively consider the use of CAPTCHA in all relevant pages.."

**Comment by mobrien** [comment]
Regarding CPU:

If you are examining each request to determine if it needs a captcha and only doing captcha for the requests that look like they are part of a DoS. Then, that is extra logic and state that will slow down the server. If you are doing CAP for every request, then it really isn't part of DoS protection, but rather part of general user auth - not necessarily site security related.

You make a good point that CAP can protect the backend against DoS.

Front-end DoS protection is really hard. You can only do so much without relying on a commercial proxy cache. Very few can fund the scale required to mitigate todays 1T+ DoS attacks. We could add a simple line to say: 

Make sure that DOS attacks on your APIs won’t cripple your site. At a minimum, have rate limiters on your slower API paths like login and token generation routines. **Consider CAPTCHA on front-end APIs to protect back-end services against DOS.**

PS. I'm going to be offline for a couple of days - so I'll be slow to respond till end of monday.

**Comment by ngkogkos** [comment]
Nice I like your suggestions there we meet in the middle :)

I understand what you say about the extra CPU processing, however a simple CAPTCHA that shows up the same user (based on IP obviously) has submitted several requests on the same page, for example contact us form, should be trivial to detect and shouldn't hinder performance. I am not a solutions architect or a developer myself though.

**Comment by virajkulkarni14** [comment]
I have updated this PR to reflect the discussion on this thread to:
"Make sure that DOS attacks on your APIs won’t cripple your site. At a minimum, have rate limiters on your slower API paths like login and token generation routines. Consider CAPTCHA on front-end APIs to protect back-end services against DOS."
Since there been no further discussion on this PR, I am closing it. Please open a new PR if you would like to take this topic up again.

Thanks! 🙂

**Pull request merged**
