### PR TITLE
Attempt to further improve Validation category

### PR DESCRIPTION
**Pull request by ngkogkos**

### CODE REVIEW

**Comment by virajkulkarni14** [comment]
@mobrien, this is the second one I'd request you to have a look at.

**Comment by mobrien** [comment]
Good additional info. Can we shrink it down a bit?

> Validate every last bit of user input following a whitelist approach on the server. Never directly display user content into responses, instead always encode user input. If user input is displayed in non-HTML code, for example if it is displayed inside JavaScript code, always enforce strict validation and ensure special characters are encoded if possible. If not, strip them off. Never use user input in SQL statements.

We want to be as terse as possible. I'm going to add separate implementation notes to each item, so we don't want to have examples etc in each item.

**Comment by ngkogkos** [comment]
Right what you say makes sense. Here is a shorter version:

> Validate every last bit of user input following a whitelist approach on the server. Never use untrusted user input in SQL statements or server-side contexts that are being evaluated. Always validate and encode user input before displaying in responses.

I can't really make this short tbh, as then misconfusion it could lead to misunderstandings. With "server-side contexts that are being evaluated" I am trying to cover the possibilities of LFI, command or templates injection and so on. Its really bad how I've put this, but couldn't come up with something better.

**Comment by virajkulkarni14** [comment]
Changed as per recommendation above and closed.

**Pull request merged**
